"""Tiny offline gazetteer: country -> (capital, nearby body of water).

Legitimate local RAG per the participant guide ("open-source, fine-tuned,
RAG-based" in-house approaches). Only well-established facts. Used by the
factual handler when the question matches the capital/water pattern; the
local model handles everything else.
"""

CAPITALS = {
    "australia": ("Canberra", "Lake Burley Griffin"),
    "united states": ("Washington, D.C.", "the Potomac River"),
    "usa": ("Washington, D.C.", "the Potomac River"),
    "canada": ("Ottawa", "the Ottawa River"),
    "united kingdom": ("London", "the River Thames"),
    "uk": ("London", "the River Thames"),
    "england": ("London", "the River Thames"),
    "france": ("Paris", "the Seine River"),
    "germany": ("Berlin", "the Spree River"),
    "italy": ("Rome", "the Tiber River"),
    "spain": ("Madrid", "the Manzanares River"),
    "portugal": ("Lisbon", "the Tagus River"),
    "netherlands": ("Amsterdam", "the Amstel River and the IJ"),
    "belgium": ("Brussels", "the Senne River"),
    "austria": ("Vienna", "the Danube River"),
    "switzerland": ("Bern", "the Aare River"),
    "poland": ("Warsaw", "the Vistula River"),
    "ukraine": ("Kyiv", "the Dnipro River"),
    "russia": ("Moscow", "the Moskva River"),
    "czech republic": ("Prague", "the Vltava River"),
    "czechia": ("Prague", "the Vltava River"),
    "slovakia": ("Bratislava", "the Danube River"),
    "hungary": ("Budapest", "the Danube River"),
    "romania": ("Bucharest", "the Dambovita River"),
    "bulgaria": ("Sofia", "the Iskar River"),
    "greece": ("Athens", "the Saronic Gulf of the Aegean Sea"),
    "turkey": ("Ankara", "the Ankara River"),
    "sweden": ("Stockholm", "Lake Malaren and the Baltic Sea"),
    "norway": ("Oslo", "the Oslofjord"),
    "denmark": ("Copenhagen", "the Oresund strait"),
    "finland": ("Helsinki", "the Gulf of Finland"),
    "iceland": ("Reykjavik", "Faxafloi Bay"),
    "ireland": ("Dublin", "the River Liffey and Dublin Bay"),
    "estonia": ("Tallinn", "the Gulf of Finland"),
    "latvia": ("Riga", "the Daugava River"),
    "lithuania": ("Vilnius", "the Neris River"),
    "belarus": ("Minsk", "the Svislach River"),
    "moldova": ("Chisinau", "the Bic River"),
    "serbia": ("Belgrade", "the Danube and Sava Rivers"),
    "croatia": ("Zagreb", "the Sava River"),
    "slovenia": ("Ljubljana", "the Ljubljanica River"),
    "bosnia and herzegovina": ("Sarajevo", "the Miljacka River"),
    "north macedonia": ("Skopje", "the Vardar River"),
    "albania": ("Tirana", "the Lana River"),
    "montenegro": ("Podgorica", "the Moraca River"),
    "china": ("Beijing", "the Yongding River"),
    "japan": ("Tokyo", "Tokyo Bay"),
    "south korea": ("Seoul", "the Han River"),
    "north korea": ("Pyongyang", "the Taedong River"),
    "india": ("New Delhi", "the Yamuna River"),
    "pakistan": ("Islamabad", "the Soan River and Rawal Lake"),
    "bangladesh": ("Dhaka", "the Buriganga River"),
    "sri lanka": ("Colombo", "the Kelani River and the Indian Ocean"),
    "nepal": ("Kathmandu", "the Bagmati River"),
    "thailand": ("Bangkok", "the Chao Phraya River"),
    "vietnam": ("Hanoi", "the Red River"),
    "laos": ("Vientiane", "the Mekong River"),
    "cambodia": ("Phnom Penh", "the Mekong and Tonle Sap Rivers"),
    "myanmar": ("Naypyidaw", "the Sittaung River basin"),
    "malaysia": ("Kuala Lumpur", "the Klang and Gombak Rivers"),
    "singapore": ("Singapore", "the Singapore Strait"),
    "indonesia": ("Jakarta", "the Ciliwung River and Jakarta Bay"),
    "philippines": ("Manila", "Manila Bay and the Pasig River"),
    "mongolia": ("Ulaanbaatar", "the Tuul River"),
    "kazakhstan": ("Astana", "the Ishim River"),
    "uzbekistan": ("Tashkent", "the Chirchiq River"),
    "kyrgyzstan": ("Bishkek", "the Chu River"),
    "tajikistan": ("Dushanbe", "the Varzob River"),
    "turkmenistan": ("Ashgabat", "the Karakum Canal"),
    "afghanistan": ("Kabul", "the Kabul River"),
    "iran": ("Tehran", "no major river; near the Alborz mountains"),
    "iraq": ("Baghdad", "the Tigris River"),
    "syria": ("Damascus", "the Barada River"),
    "lebanon": ("Beirut", "the Mediterranean Sea"),
    "israel": ("Jerusalem", "no major body of water; in the Judaean Mountains"),
    "jordan": ("Amman", "the Zarqa River basin"),
    "saudi arabia": ("Riyadh", "the Wadi Hanifa"),
    "united arab emirates": ("Abu Dhabi", "the Persian Gulf"),
    "uae": ("Abu Dhabi", "the Persian Gulf"),
    "qatar": ("Doha", "the Persian Gulf"),
    "kuwait": ("Kuwait City", "the Persian Gulf"),
    "bahrain": ("Manama", "the Persian Gulf"),
    "oman": ("Muscat", "the Gulf of Oman"),
    "yemen": ("Sanaa", "no major body of water; in the highlands"),
    "egypt": ("Cairo", "the Nile River"),
    "libya": ("Tripoli", "the Mediterranean Sea"),
    "tunisia": ("Tunis", "the Lake of Tunis and the Mediterranean Sea"),
    "algeria": ("Algiers", "the Mediterranean Sea"),
    "morocco": ("Rabat", "the Bou Regreg River and the Atlantic Ocean"),
    "sudan": ("Khartoum", "the confluence of the Blue and White Nile"),
    "ethiopia": ("Addis Ababa", "the Akaki River"),
    "kenya": ("Nairobi", "the Nairobi River"),
    "tanzania": ("Dodoma", "no major body of water; inland plateau"),
    "uganda": ("Kampala", "Lake Victoria"),
    "rwanda": ("Kigali", "the Nyabarongo River"),
    "nigeria": ("Abuja", "the Usuma River"),
    "ghana": ("Accra", "the Gulf of Guinea"),
    "ivory coast": ("Yamoussoukro", "Lake Kossou region"),
    "senegal": ("Dakar", "the Atlantic Ocean"),
    "south africa": ("Pretoria", "the Apies River"),
    "zimbabwe": ("Harare", "Lake Chivero region"),
    "zambia": ("Lusaka", "no major river; on a plateau"),
    "mozambique": ("Maputo", "Maputo Bay of the Indian Ocean"),
    "angola": ("Luanda", "the Atlantic Ocean"),
    "democratic republic of the congo": ("Kinshasa", "the Congo River"),
    "republic of the congo": ("Brazzaville", "the Congo River"),
    "cameroon": ("Yaounde", "the Mfoundi River"),
    "brazil": ("Brasilia", "Lake Paranoa"),
    "argentina": ("Buenos Aires", "the Rio de la Plata"),
    "chile": ("Santiago", "the Mapocho River"),
    "peru": ("Lima", "the Rimac River and the Pacific Ocean"),
    "colombia": ("Bogota", "the Bogota River"),
    "venezuela": ("Caracas", "the Guaire River"),
    "ecuador": ("Quito", "the Machangara River"),
    "bolivia": ("La Paz", "the Choqueyapu River"),
    "paraguay": ("Asuncion", "the Paraguay River"),
    "uruguay": ("Montevideo", "the Rio de la Plata"),
    "mexico": ("Mexico City", "Lake Texcoco basin"),
    "cuba": ("Havana", "Havana Bay and the Gulf of Mexico"),
    "jamaica": ("Kingston", "Kingston Harbour of the Caribbean Sea"),
    "haiti": ("Port-au-Prince", "the Gulf of Gonave"),
    "dominican republic": ("Santo Domingo", "the Ozama River"),
    "guatemala": ("Guatemala City", "no major body of water; in a mountain valley"),
    "panama": ("Panama City", "the Gulf of Panama"),
    "costa rica": ("San Jose", "the Torres River"),
    "new zealand": ("Wellington", "Wellington Harbour of the Cook Strait"),
    "fiji": ("Suva", "the Pacific Ocean"),
    "papua new guinea": ("Port Moresby", "the Gulf of Papua"),
}

import re

_DISPLAY = {
    "usa": "the United States",
    "united states": "the United States",
    "uk": "the United Kingdom",
    "united kingdom": "the United Kingdom",
    "uae": "the United Arab Emirates",
    "united arab emirates": "the United Arab Emirates",
    "netherlands": "the Netherlands",
    "philippines": "the Philippines",
    "czech republic": "the Czech Republic",
    "dominican republic": "the Dominican Republic",
    "democratic republic of the congo": "the Democratic Republic of the Congo",
    "republic of the congo": "the Republic of the Congo",
}


def lookup_capital(question: str):
    """If the question asks about a country's capital, return
    (country_display, capital, water) else None."""
    q = question.lower()
    if "capital" not in q:
        return None
    for country in sorted(CAPITALS, key=len, reverse=True):
        if re.search(rf"\b{re.escape(country)}\b", q):
            cap, water = CAPITALS[country]
            disp = _DISPLAY.get(country, country.title())
            return disp, cap, water
    return None
